config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	validates :name, length: { minimum: 3}
	validates :price, :description, :address, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end
	
	def create
		Item.create(place_params)
		redirect_to root_path
	end

	private

	def place_params
		params.require(:item).permit(:name, :price, :description, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1>Declutr</h1>
<h2>"Let someone else take away that clutter in your home"</h2>

<% @items.each do |item| %>
  <div class="hyphy-box col-10 offset-1">
    <h1><%= link_to item.name, item_path(item) %></h1><br />
    <h2><%= item.price %></h2><br /><br />
    <i><%= item.address %></i><br /><br />
    <p><%= item.description %></p><br />
  </div>
<% end %>

app/views/items/new.html.erb
<div class="hyphy-box col-10 offset-1">
	<h1>Enter Your Place Details</h1>
		<%= simple_form_for @item do |f| %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :address %>
    <br />
    <%= f.submit 'List My Product', class: 'btn btn-primary' %>
  <% end %>
	<br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Declutr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Declutr</a>
    <%= link_to 'Declutr', root_path, class: 'navbar-brand' %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
        <%= link_to 'New Item', new_item_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    
    <%= yield %>
  
  </body>
</html>